package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;

/**
 * TGames generated by hbm2java
 */
public class TGames  implements java.io.Serializable {

     @GeneratedValue
     private Integer id;
     private TLanguages TLanguages;
     private TUsers TUsers;
     private String vtitle;
     private Date dcreatedate;
     private String vstatus;
     private Integer nrate;
     private Integer nviewcount;
     private String vimagepath;

    public TGames() {
    }

	
    public TGames(Integer id) {
        this.id = id;
    }
    public TGames(Integer id, TLanguages TLanguages, TUsers TUsers, String vtitle, Date dcreatedate, String vstatus, Integer nrate, Integer nviewcount, String vimagepath) {
       this.id = id;
       this.TLanguages = TLanguages;
       this.TUsers = TUsers;
       this.vtitle = vtitle;
       this.dcreatedate = dcreatedate;
       this.vstatus = vstatus;
       this.nrate = nrate;
       this.nviewcount = nviewcount;
       this.vimagepath = vimagepath;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TLanguages getTLanguages() {
        return this.TLanguages;
    }
    
    public void setTLanguages(TLanguages TLanguages) {
        this.TLanguages = TLanguages;
    }
    public TUsers getTUsers() {
        return this.TUsers;
    }
    
    public void setTUsers(TUsers TUsers) {
        this.TUsers = TUsers;
    }
    public String getVtitle() {
        return this.vtitle;
    }
    
    public void setVtitle(String vtitle) {
        this.vtitle = vtitle;
    }
    public Date getDcreatedate() {
        return this.dcreatedate;
    }
    
    public void setDcreatedate(Date dcreatedate) {
        this.dcreatedate = dcreatedate;
    }
    public String getVstatus() {
        return this.vstatus;
    }
    
    public void setVstatus(String vstatus) {
        this.vstatus = vstatus;
    }
    public Integer getNrate() {
        return this.nrate;
    }
    
    public void setNrate(Integer nrate) {
        this.nrate = nrate;
    }
    public Integer getNviewcount() {
        return this.nviewcount;
    }
    
    public void setNviewcount(Integer nviewcount) {
        this.nviewcount = nviewcount;
    }
    public String getVimagepath() {
        return this.vimagepath;
    }
    
    public void setVimagepath(String vimagepath) {
        this.vimagepath = vimagepath;
    }




}


