package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1




/**
 * TGenres generated by hbm2java
 */
public class TGenres  implements java.io.Serializable {


     private Integer id;
     private String vname;

    public TGenres() {
    }

	
    public TGenres(Integer id) {
        this.id = id;
    }
    public TGenres(Integer id, String vname) {
       this.id = id;
       this.vname = vname;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVname() {
        return this.vname;
    }
    
    public void setVname(String vname) {
        this.vname = vname;
    }




}


