package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * TLanguages generated by hbm2java
 */
public class TLanguages  implements java.io.Serializable {


     private Integer id;
     private String vname;
     private Set<TGames> TGameses = new HashSet<TGames>(0);

    public TLanguages() {
    }

	
    public TLanguages(Integer id) {
        this.id = id;
    }
    public TLanguages(Integer id, String vname, Set<TGames> TGameses) {
       this.id = id;
       this.vname = vname;
       this.TGameses = TGameses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVname() {
        return this.vname;
    }
    
    public void setVname(String vname) {
        this.vname = vname;
    }
    public Set<TGames> getTGameses() {
        return this.TGameses;
    }
    
    public void setTGameses(Set<TGames> TGameses) {
        this.TGameses = TGameses;
    }




}


