package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1



/**
 * TLikes generated by hbm2java
 */
public class TLikes  implements java.io.Serializable {


     private Integer id;
     private TUsers TUsersByNuserid;
     private TUsers TUsersByNgameid;

    public TLikes() {
    }

	
    public TLikes(Integer id) {
        this.id = id;
    }
    public TLikes(Integer id, TUsers TUsersByNuserid, TUsers TUsersByNgameid) {
       this.id = id;
       this.TUsersByNuserid = TUsersByNuserid;
       this.TUsersByNgameid = TUsersByNgameid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TUsers getTUsersByNuserid() {
        return this.TUsersByNuserid;
    }
    
    public void setTUsersByNuserid(TUsers TUsersByNuserid) {
        this.TUsersByNuserid = TUsersByNuserid;
    }
    public TUsers getTUsersByNgameid() {
        return this.TUsersByNgameid;
    }
    
    public void setTUsersByNgameid(TUsers TUsersByNgameid) {
        this.TUsersByNgameid = TUsersByNgameid;
    }




}


