package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TRoles generated by hbm2java
 */
public class TRoles  implements java.io.Serializable {


     private Integer id;
     private String vname;
     private Set<TUsers> TUserses = new HashSet<TUsers>(0);

    public TRoles() {
    }

	
    public TRoles(Integer id) {
        this.id = id;
    }
    public TRoles(Integer id, String vname, Set<TUsers> TUserses) {
       this.id = id;
       this.vname = vname;
       this.TUserses = TUserses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVname() {
        return this.vname;
    }
    
    public void setVname(String vname) {
        this.vname = vname;
    }
    public Set<TUsers> getTUserses() {
        return this.TUserses;
    }
    
    public void setTUserses(Set<TUsers> TUserses) {
        this.TUserses = TUserses;
    }




}


