package com.master.roleup.model;
// Generated 10.11.2014 21:53:41 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * TUsers generated by hbm2java
 */
public class TUsers  implements java.io.Serializable {


     private Integer id;
     private TRoles TRoles;
     private String vlogin;
     private String vpasswordhash;
     private String vfullname;
     private String vcountry;
     private Set<TLikes> TLikesesForNuserid = new HashSet<TLikes>(0);
     private Set<TGames> TGameses = new HashSet<TGames>(0);
     private Set<TLikes> TLikesesForNgameid = new HashSet<TLikes>(0);

    public TUsers() {
    }

	
    public TUsers(Integer id) {
        this.id = id;
    }
    public TUsers(Integer id, TRoles TRoles, String vlogin, String vpasswordhash, String vfullname, String vcountry, Set<TLikes> TLikesesForNuserid, Set<TGames> TGameses, Set<TLikes> TLikesesForNgameid) {
       this.id = id;
       this.TRoles = TRoles;
       this.vlogin = vlogin;
       this.vpasswordhash = vpasswordhash;
       this.vfullname = vfullname;
       this.vcountry = vcountry;
       this.TLikesesForNuserid = TLikesesForNuserid;
       this.TGameses = TGameses;
       this.TLikesesForNgameid = TLikesesForNgameid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TRoles getTRoles() {
        return this.TRoles;
    }
    
    public void setTRoles(TRoles TRoles) {
        this.TRoles = TRoles;
    }
    public String getVlogin() {
        return this.vlogin;
    }
    
    public void setVlogin(String vlogin) {
        this.vlogin = vlogin;
    }
    public String getVpasswordhash() {
        return this.vpasswordhash;
    }
    
    public void setVpasswordhash(String vpasswordhash) {
        this.vpasswordhash = vpasswordhash;
    }
    public String getVfullname() {
        return this.vfullname;
    }
    
    public void setVfullname(String vfullname) {
        this.vfullname = vfullname;
    }
    public String getVcountry() {
        return this.vcountry;
    }
    
    public void setVcountry(String vcountry) {
        this.vcountry = vcountry;
    }
    public Set<TLikes> getTLikesesForNuserid() {
        return this.TLikesesForNuserid;
    }
    
    public void setTLikesesForNuserid(Set<TLikes> TLikesesForNuserid) {
        this.TLikesesForNuserid = TLikesesForNuserid;
    }
    public Set<TGames> getTGameses() {
        return this.TGameses;
    }
    
    public void setTGameses(Set<TGames> TGameses) {
        this.TGameses = TGameses;
    }
    public Set<TLikes> getTLikesesForNgameid() {
        return this.TLikesesForNgameid;
    }
    
    public void setTLikesesForNgameid(Set<TLikes> TLikesesForNgameid) {
        this.TLikesesForNgameid = TLikesesForNgameid;
    }




}


